---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client

spec:
  selector:
    matchLabels:
      app: client

  template:
    metadata:
      labels:
        app: client

    spec:
      containers:
        - name: tools
          image: giantswarm/tiny-tools
          command:
            - 'sh'
            - '-c'
            - 'while true; do sleep 5; done'
