---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway

  template:
    metadata:
      labels:
        app: gateway

    spec:
      containers:
        - name: gateway
          image: gateway:west
          args:
            - -ca=/certs/tls.ca
            - -cert=/certs/tls.crt
            - -key=/certs/tls.key

          volumeMounts:
            - mountPath: /certs
              name: gateway-certs

      volumes:
        - name: gateway-certs
          secret:
            secretName: gateway-certs
